name: Workflow Caller

on:
    push:
        branches:
            - main

jobs:
    some-job:
        uses: ./.github/workflows/reusable.yaml
        with:
            ENVIRONMENT: myenv
        secrets:
            NAME: ${{ secrets.NAME }}